# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://s3rgi.github.io/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2021–2022, Sergi Navas and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "ca"
#[languages]
#config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
